expid: NYC-Traffic
runs: 1
log_level: INFO

base_path: data/NYC/
dataset_name: dataset_nyc.npz

model_name: TGCSRN

seed: 666
#test_only: False
test_only: True
device: cuda:2

data:
  dataset_contents: nyc51_all
  freq: 30min
  cluster_num: 51
  poi_cluster: 4
  train_batch_size: 64
  test_batch_size: 64
  val_batch_size: 64
  points_per_hour: 2
  num_for_predict: 8
  num_for_target: 3
  num_shift: 0
  use_external: False
  num_of_weeks: 0
  num_of_days: 0
  num_of_hours: 1

model:
  input_dim: [ 4 ]
  hidden_dim: 64
  output_dim: 4
  context_channels: [ 3, 16 ]
  context_dims: [ 32, 32 ]
  d_model_cluster: 64
  retention_rate: 0.1
  gcn_depth: 2
  norm_graph: sym
  dropout_prob: 0.2
  activation_type: relu
  fuse_type: sum
  use_skip: False
  use_weather: False
  use_adaptive: True
  node_emb: 10

train:
  base_lr: 0.001
  weight_decay: 0.0001
  milestones: [ 50, 90, 130, 170 ]
  lr_decay_ratio: 0.5
  min_learning_rate: 2.0e-06
  max_grad_norm: 5
  load_initial: False
  tolerance: 50
  epoch_start: 0
  epochs: 200
  global_step: 0
  print_every: 1
  description: NYC51 8-3

  best_mode: data/NYC/best/exp_nyc.pth
  best_mat: data/NYC/mat/mat_nyc.pth